---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-webhook-config
data:
  conf.hcl: |
    mirror {
        k8s.gcr.io = "registry.aliyuncs.com/google_containers"
        gcr.io = "registry.aliyuncs.com/google_containers"
        quay.io = "quay-mirror.qiniu.com"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mirror-webhook
  name: mirror-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-webhook
  template:
    metadata:
      labels:
        app: mirror-webhook
    spec:
      containers:
      - name: mirror-webhook
        image: docker.pkg.github.com/acteq/k8s-mirror/mirror
        imagePullPolicy: IfNotPresent
        command: ["webhook"]
        args:  ["--conf=/etc/mirror/conf.hcl","--tls-cert-file=/etc/mirror/pki/tls.crt", "--tls-private-key-file=/etc/mirror/pki/tls.key"]
        volumeMounts:
          - mountPath: "/etc/mirror/"
            name: conf
          - mountPath: /etc/mirror/pki
            name: pki
      volumes:
        - name: conf
          configMap:
            name: mirror-webhook-config
        - name: pki
          secret:
            secretName: mirror-webhook-tls

---
apiVersion: v1
kind: Service
metadata:
  name: mirror-service
spec:
  selector:
    app: mirror-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443