apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mirror-webhook
  name: mirror-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-webhook
  template:
    metadata:
      labels:
        app: mirror-webhook
    spec:
      nodeName: node4
      containers:
      - name: mirror-webhook
        image: k8s-mirror
        imagePullPolicy: IfNotPresent
        command: ["webhook"]
        args:  ["-tls-cert-file=/etc/kubernetes/pki/ca.pem", "-tls-private-key-file=/etc/kubernetes/pki/ca-key.pem"]
        volumeMounts:
          - mountPath: "/etc/kubernetes/pki"
            name: pki
      volumes:
        - name: pki
          hostPath:
            path: /data/cloud/pki


---
apiVersion: v1
kind: Service
metadata:
  name: mirror-service
spec:
  selector:
    app: mirror-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443