---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-webhook-config
data:
  conf.hcl: |
    mirror {
        gcr.io = "registry.aliyuncs.com/google_containers"
        k8s.gcr.io = "registry.aliyuncs.com/google_containers"
        quay.io = "quay-mirror.qiniu.com"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mirror-webhook
  name: mirror-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-webhook
  template:
    metadata:
      labels:
        app: mirror-webhook
    spec:
      containers:
      - name: mirror-webhook
        image: acte/k8s-mirror
        imagePullPolicy: Always
        command: ["/app/goapp"]
        args:  ["--conf=/etc/mirror/conf.hcl","--tls-cert-file=/etc/mirror/pki/tls.crt", "--tls-private-key-file=/etc/mirror/pki/tls.key"]
        volumeMounts:
          - mountPath: "/etc/mirror/"
            name: conf
          - mountPath: /etc/mirror/pki
            name: pki
      volumes:
        - name: conf
          configMap:
            name: mirror-webhook-config
        - name: pki
          secret:
            secretName: mirror-webhook-tls

---
apiVersion: v1
kind: Service
metadata:
  name: mirror-webhook
spec:
  selector:
    app: mirror-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation-mirror-webhook
webhooks:
  - name: mirror-webhook.default.svc
    clientConfig:
      service:
        name: mirror-webhook
        namespace: default
        path: "/mutate"
    # caBundle: ${CA_BUNDLE}
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0VENDQXAyZ0F3SUJBZ0lUY2RRanhJc3U5YjRYM09xZ3IxdVhsQUd4QVRBTkJna3Foa2lHOXcwQkFRc0YKQURCek1Rc3dDUVlEVlFRR0V3SkRUakVSTUE4R0ExVUVDQk1JVTJoaGJtZG9ZV2t4RVRBUEJnTlZCQWNUQ0ZObwpZVzVuYUdGcE1STXdFUVlEVlFRS0V3cExkV0psY201bGRHVnpNUm93R0FZRFZRUUxFeEZMZFdKbGNtNWxkR1Z6CkxXMWhiblZoYkRFTk1Bc0dBMVVFQXhNRVpYUmpaREFlRncweU1EQTRNamd3TWpJeU1EQmFGdzB5TlRBNE1qY3cKTWpJeU1EQmFNSE14Q3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSUV3aFRhR0Z1WjJoaGFURVJNQThHQTFVRQpCeE1JVTJoaGJtZG9ZV2t4RXpBUkJnTlZCQW9UQ2t0MVltVnlibVYwWlhNeEdqQVlCZ05WQkFzVEVVdDFZbVZ5CmJtVjBaWE10YldGdWRXRnNNUTB3Q3dZRFZRUURFd1JsZEdOa01JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0MKQVE4QU1JSUJDZ0tDQVFFQTJhTCs0dVVsQ282QWtvYm5hR0RnZG4wd3VaeDgxMFJFd0U3dlhrREdtVFY5MTl1Kwo5Misrd0RLU09ucC80anFKYTByM1FCcEVNN1dDMDB1L29Xb3U3SEJ6OVBtSzRyVmhqNTBMUzVJZXhhNGxFTE1CCjl2WWNNc0MrSzBuTGZkQ0RicnNJYUFBckIrQWd3MkF3L1R5aWVLMWJpNkVXSjJBTSsxdjEwT2dsSGF2TnA2akcKclRFQnRXWU9KK2tGR2Y2ckIzOEwwdWF2M2FrenAxQVJXVzJvTEhaelZvejlmYWh4OTZObXY1WHAyMzMrYVAvdgo0UjFmbzFRUjdjdCtSYk9BU1NuQ0NIQVZneWkzRUVWMUxEeS9pcTNJdTZ1N3VlVDJxYzU3OThFd3F3cGc2dGd4ClhVeXRodTRwcEg1V0lVOGQyZjVNbXpIMlNLbDBvVjZaNWdGaDV3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVOWHpCZUdNWjlQd1VMY210dzN1eQpUY0JuUTJZd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLVXVKTi9VNXZZbHdaZ3Q4SHhhKzhsS0NvMU42T09mCmV6eGljbDVYS2p0QWVRZXVtSlpUYjJzWEkwbUpCVmlveXlSKzN1RWpLaVZ2eWlaSTJaaXoybGRkc0EvNm94VWwKQ3NhcHdTWjdvVStZbEZqYkh6c2JpNm52UlZPcWNSSEtEeUxRUTdweXRLYjQ1Zlk3UUFvNDdIbVdicW82QUtuVwpqRlZ6QUU4ZDFzNTNjck82RU9rdFZQWUQzZldvSEg5L0xJM0pvZDdyMVJiUzRqVlM2eXBBUGtZUXRpcGU4RGdMCm5BVHBiaVAwNFBBdGJzNHlNUFNOQ3gvQ2R1NUFidEp6dDErMGpoMTlBakxlbEJ3bFQvaEdYbXRpUFpZckNLVnMKYTMrWmJCR1oxa0IzREREV1VycE5OVTlJTGxXQVhFalduazJ0SGpIS0ZSYkdPSzhJYzZTMlFuST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods", "deployments"]
        scope: "*"
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
